### ISSUE TITLE
Create an example with NadamAccum

### ISSUE THREAD

**Issue by raghakot** [the-moliver/kfs#1]
It would be useful to create a simple example comparing accum on smaller batches vs full batch size on a regular Nadam. I tried your optimizer out and the results are not the same. Accum version performs a lot worse. Ex: Accum with batch size=2 for 8 accum_iters is nowhere close to results from Nadam with batchSize 16

**Comment by the-moliver** [comment]
@raghakot I just tried on the Keras MNIST example with the only changes:
```python
batch_size = 128/8
opt = NadamAccum(accum_iters=8)
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=opt,
              metrics=['accuracy'])
```
and it seemed very comparable to using `opt = Nadam()` with `batch_size = 128`. Can you show me an example where this is not the case?
