### ISSUE TITLE
Nadamaccum problem when saving model and how to fix it

### ISSUE THREAD

**Issue by alalbiol** [the-moliver/kfs#6]
When saving a model that uses Nadamaccum there is a problem with accum_iters that says that the object can't be serialized into json

I think that the fix is really easy by changing one line:

Line 184 in optimizers.py -> 'accum_iters': self.accum_iters}
should change to:
'accum_iters': float(K.get_value(self.accum_iters)),

**Comment by the-moliver** [comment]
Fixed
